spring:
  datasource:
    url: jdbc:mysql://${LOCAL_DB_ENDPOINT}/hotdeal_ecommerce_user_address?useSSL=false&allowPublicKeyRetrieval=true
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: localhost
      port: 6379
      username: ${REDIS_LOCAL_USERNAME}
      password: ${REDIS_LOCAL_PASSWORD}
