spring:
  datasource:
    url: jdbc:mysql://${LOCAL_DB_ENDPOINT}/hotdeal_ecommerce_product_review
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  kafka:
    bootstrap-servers: ${LOCAL_KAFKA_ENDPOINT}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topics:
      reduce-quantity: ${KAFKA_REDUCE_QUANTITY_TOPIC}
      rollback-reduce-quantity: ${KAFKA_ROLLBACK_REDUCE_QUANTITY_TOPIC}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
