spring:
  application:
    name: product-service
  profiles:
    active: ${ACTIVE_PROFILE}
logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 19093

#openapi:
#  service:
#    url: http://localhost:19091/product-service

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

admin:
  user-id: ${ADMIN_USER_ID}
  email: ${ADMIN_EMAIL}
  role: ${ADMIN_ROLE}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
    prometheus:
      access: unrestricted