spring:
  application:
    name: product-service
  profiles:
    active: ${ACTIVE_PROFILE}
logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 19093

#openapi:
#  service:
#    url: http://localhost:19091/product-service

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

admin:
  user-id: ${ADMIN_USER_ID}
  email: ${ADMIN_EMAIL}
  role: ${ADMIN_ROLE}

s3:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  bucket-name: ${AWS_S3_BUCKET_NAME}
  region: ${AWS_REGION}
  domain: ${AWS_DOMAIN}