spring:
  datasource:
    url: jdbc:mysql://${LOCAL_DB_ENDPOINT}/hotdeal_ecommerce_order
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  kafka:
    bootstrap-servers: ${LOCAL_KAFKA_ENDPOINT}
    consumer:
      bootstrap-servers: ${LOCAL_KAFKA_ENDPOINT}  # 컨슈머에도 명시적으로 설정
    producer:
      bootstrap-servers: ${LOCAL_KAFKA_ENDPOINT}  # 프로듀서에도 명시적으로 설정
  data:
    redis:
      host: ${REDIS_LOCAL_HOST}
      port: ${REDIS_LOCAL_PORT}
      username: ${REDIS_LOCAL_USERNAME}
      password: ${REDIS_LOCAL_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/