spring:
  application:
    name: order-service
  profiles:
    active: ${ACTIVE_PROFILE}

server:
  port: 19094

logging:
  level:
    org.springframework.security: DEBUG

admin:
  user-id: ${ADMIN_USER_ID}
  email: ${ADMIN_EMAIL}
  role: ${ADMIN_ROLE}

springdoc:
   api-docs:
     enabled: true
   swagger-ui:
     path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
    prometheus:
      access: unrestricted