server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**, /api/v1/address/**, /api/v1/address-default/**

        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/api/v1/companies/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**, /api/v1/promotions/**, /api/v1/reviews/**

        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/api/v1/coupons/**, /api/v1/couponInfos/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**, /api/v1/baskets/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}