name: Build & Deploy with Docker Compose

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to EC2 and run Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # 프로젝트 디렉토리로 이동
            cd /home/ubuntu/HotDealWave
            
            # Git 저장소에서 최신 코드 가져오기
            git pull origin main
            
            # 기존 컨테이너 중지 및 제거
            docker-compose down
            
            # Docker Compose 빌드 및 실행
            docker-compose up --build -d
